// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65tWdOpVFUmRWs1SMMXH_JZN4m1me7dA',
    appId: '1:681269026851:web:77c00c975bea8715fc5196',
    messagingSenderId: '681269026851',
    projectId: 'gerobaks',
    authDomain: 'gerobaks.firebaseapp.com',
    storageBucket: 'gerobaks.firebasestorage.app',
    measurementId: 'G-QDVEWDRQYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7s_mX2GmLGMOU6ytrgKh7fwU4FhIiLMU',
    appId: '1:681269026851:android:18f0182298ff71f0fc5196',
    messagingSenderId: '681269026851',
    projectId: 'gerobaks',
    storageBucket: 'gerobaks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZb9gOO25z_NtybPD42XhFCG0m67Ud6uk',
    appId: '1:681269026851:ios:66fc58148b8a1723fc5196',
    messagingSenderId: '681269026851',
    projectId: 'gerobaks',
    storageBucket: 'gerobaks.firebasestorage.app',
    iosBundleId: 'com.example.bankSha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZb9gOO25z_NtybPD42XhFCG0m67Ud6uk',
    appId: '1:681269026851:ios:66fc58148b8a1723fc5196',
    messagingSenderId: '681269026851',
    projectId: 'gerobaks',
    storageBucket: 'gerobaks.firebasestorage.app',
    iosBundleId: 'com.example.bankSha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC65tWdOpVFUmRWs1SMMXH_JZN4m1me7dA',
    appId: '1:681269026851:web:5ca5cb59a8e0889afc5196',
    messagingSenderId: '681269026851',
    projectId: 'gerobaks',
    authDomain: 'gerobaks.firebaseapp.com',
    storageBucket: 'gerobaks.firebasestorage.app',
    measurementId: 'G-05FPRF9E7P',
  );
}
